encoding: utf-8

# SEO相关信息
title: Taihua's Blog
description: Taihua的个人博客
keywords: Taihua,Blog,Java,Html,JavaScript
author: Taihua
footerText: 'Copyright ©2020 by Taihua'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://secretpolice1995.github.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/142217

# 菜单
menu:
  - title: 首页
    url: /
  - title: 文章
    url: /pages/articles.html
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html


# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: true

extTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: TMaize的个人博客
    url: http://blog.tmaize.net
  - title: 文科中的技术宅
    url: https://www.townwang.com
  - title: 阮一峰的网络日志
    url: http://www.ruanyifeng.com/blog
  - title: 菜鸟教程
    url: https://www.runoob.com
  - title: 老殁|殁漂遥
    url: https://www.mpyit.com
  - title: 吾爱分享
    url: https://52sharing.cn
  - title: 乌云资源
    url: http://www.wuyunzy.cn
  - title: 胡萝卜周
    url: http://www.carrotchou.blog
  - title: AMiner
    url: https://www.aminer.cn   